### ISSUE TITLE
Add Tchaikovsky P I Opus 39 #16 "Old French Song"

### ISSUE THREAD

**Issue by mapadofu** [MutopiaProject/MutopiaProject#546]
I plan on typesetting this one, new content.
Can you assign this to me?

**Comment by glenl** [comment]
I have sent you a request to join our contributor team, I can "officially" assign this task to you when you accept. Creating a task and getting assigned is added insurance that another contributor isn't typesetting the same work.

**Comment by mapadofu** [comment]
This has been sitting in the pull requests queue for several months https://github.com/MutopiaProject/MutopiaProject/pull/548

**Comment by glenl** [comment]
This may be due to the copyright of your source. Although the publication
date is 1948, it is an urtext edition and qualifies as public domain, as I
understand it, since it is older than 25 years. But I know that this date
would have initiated a review of the source edition.

There is a scanned publication that fully meets Mutopia requirements on
IMSLP (New York: G. Schirmer, 1904. Plate 17224
<http://imslp.org/wiki/Special:ImagefromIndex/07996>). If your
transcription matches that one sufficiently you could simply modify your
source specification.

**Comment by dominicus** [comment]
published
