### ISSUE TITLE
Search function unable to match accented characters to unaccented search terms

### ISSUE THREAD

**Issue by dominicus** [MutopiaProject/MutopiaProject#553]
The searchbox function in Mutopia website is accent-sensitive, when it shouldn't be.  Thus:
 -   a search for "dvorak" yields no pieces by composer Dvořák
 -   a search for "debussy prelude" yields no records

**Comment by glenl** [comment]
OMG. I just flashed on an editor I used in the mid 80's (!) that had the command,

`set search diacritical insensitive`

I'd like full text search as well.

**Comment by glenl** [comment]
I noticed this issue recently and I wanted to comment with some thoughts about it. It probably contributes little towards fixing this with our current lookup mechanism.

In most databases, what you describe is done with an additional column or table that is used solely as search criteria. In most flavors of SQL, you would then create a virtual table with the search criteria and the matching original row-id so that you could use the full text search (fts) ``MATCH`` keyword. The new schema might look like this,
````
CREATE TABLE muComposer (
    composer TEXT PRIMARY KEY,
    description TEXT NOT NULL,
    search_terms TEXT
    ) WITHOUT ROWID;
````
and the virtual table used to do fts,
````
CREATE VIRTUAL TABLE muVComposer
    USING fts3(composer,search_terms);
````
And finally, a possible search_terms column entry for Dvorak might be
````
DvorakA Anton Antonin Dvorak Dvořák Czech Republic
````
All of the following searches would return DvorakA,
````
SELECT composer FROM muVComposer WHERE search_terms MATCH 'Dvořák';
SELECT composer FROM muVComposer WHERE search_terms MATCH 'Dvorak';
SELECT composer FROM muVComposer WHERE search_terms MATCH 'DvorakA';
SELECT composer FROM muVComposer WHERE search_terms MATCH 'Antonin Dvořák';
````
Note that you would want to create the ``search_terms`` value by hand because simply removing accents is precarious. An  example is MuellerAE and MuellerW. Both of these would match to "Müller" but the ``search_terms`` value should additionally include both "Mueller" as well as "Muller".

Matching on something like "Debussy Prelude" requires that a similar strategy is done with pieces. You might do something like this with piece 1956 (Prélude 1: Danseuses de Delphes),
````
Prelude 1 Dancers of Delphi Prélude 1 Danseuses de Delphes
... or even,
DebussyC Claude Debussy Prelude 1 Dancers of Delphi Prélude Danseuses de Delphes
````
You might even include common misspellings. We have lots of pieces but it makes a relatively small database. Even with good normalization you might want to throw lots of keywords into the ``search_terms`` value. In fact, I might suggest keeping the search terms in a completely separate table to make them more manageable. This will add some bulk --- fts builds several index tables from the search terms you give it --- but it is still a small-ish database.

**Comment by dominicus** [comment]
I recently updated "Für Elise", as my daughter is learning it now.  Searching for "fur elise" came empty, so I decided to add this to the "more info" header.  Not elegant, but it's found now.
Just based on trial/error, the scope of the search feature seems to be almost limited to the content of .rdf files.  I say "almost" because rdf-only doesn't  explain all the hits for "alma".
My mind was heading in the direction of your earlier post, as there are plenty of functions on the web for diacritical removal.
What about having the script for .rdf generate a list of unique keywords into a rdf-only field with diacriticals removed, and append that to the end of the .rdf?
The value of ignoring diacriticals is ease of implementation with limited risk of false hits.

**Comment by glenl** [comment]
What's with the matches for "alma"? At the top is a hit for Aguado op4 no. 1, so I built the entire piece along with the rdf and got no matches to with a ``grep -i alma *``. "alma" is not in the log either. I might take a look at this today; it is really odd. I don't think it has to do with your name because either one of "javier" and "ruiz" return 4 matches.

**Comment by chrissawer** [comment]
It looks like perl search code concatenates a load of fields together before doing the pattern match, so alma comes from the concatenation of Classical and Mainz - a search for classicalmainz finds the same piece. Would be nice to get this fixed along with the original bug report of accented characters.
FYI for anyone wanting to fix this, our server is Centos 6 with perl v5.10.1.

**Comment by glenl** [comment]
And now that I have found where this is done (make-table.cgi, ~line 124) and "instrument" precedes "date" I can find all guitar pieces dated in the 1800's by searching "tar18". Perhaps it is a feature? So, yes, this could be fixed by stuffing some character ("|", perhaps) between all the search terms.

I would suggest fixing this independently of the diacritical search fix since there are other details to consider. Eventually, the fix in perl will be to do the matching with a unicode collator:
```perl
use 5.014;
use utf8;
use Unicode::Collate;

#binmode STDOUT, ':encoding(UTF-8)';
my $str  = "Îñţérñåţîöñåļîžåţîöñ";
my $look = "natIONaliz";
my $Collator = Unicode::Collate->new( normalization => undef, level => 1 );
my @match = $Collator->match($str, $look);

print "matches\n" if @match;
```
This collator is also case insensitive; a good thing since idioms like ``tr/a-z/A-Z`` only work on 26 characters in the unicode character set. It would be wise to do performance testing with this since we are doing a linear search.

**Comment by glenl** [comment]
Since the "alma" search problem is a separate issue unrelated to diacritical search, I have created a new issue, #659 .

**Comment by dominicus** [comment]
Closing this one.
Remaining issue related to diacritical search is now tracked in MutopiaWeb issue tracker:
https://github.com/MutopiaProject/MutopiaWeb/issues/81
